spring:
  datasource:
    url: jdbc:postgresql://127.0.0.7:5432/catastro
    username: postgres
    password: 1234
    platform: postgres
    driver-class-name: org.postgresql.Driver
    
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database: POSTGRESQL
    show-sql: true
