spring:
  datasource:
    url: jdbc:postgresql://127.0.0.7:5432/catastro
    username: postgres
    password: 1234
    platform: postgres
	driverClassName: org.postgresql.Driver
    
  jpa:
    database: POSTGRESQL
    show-sql: true
