server:
  port: 8888

spring:
  application:
    name: catastro-microservices
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Xndy/catastro-microservices
          
          
